[pytest]
testpaths = tests
python_files = test_*.py
python_functions = test_*
addopts = -v

# Ignore directories that shouldn't be tested
norecursedirs =
    .git
    .github
    .ipynb_checkpoints
    __pycache__
    .idea
    .vscode
    .venv
    venv
